### ISSUE TITLE
shm-size when run horovod with pytorch

### ISSUE THREAD

**Issue by tingweiwu** [horovod/horovod#1081]
**Environment:**
1. Framework: (TensorFlow, Keras, PyTorch, MXNet)
PyTorch
2. Framework version:
1.0.0
3. Horovod version:
0.15.2
4. MPI version:
mpirun.real (OpenRTE) 3.1.2
5. CUDA version:
9.0
6. NCCL version:
7. Python version:
3.5
8. OS and version:

**Checklist:**
1. Did you search issues to find if somebody asked this question before?
yes. I search `insufficient shared memory`
2. If your question is about hang, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/running.md)?
yes
3. If your question is about docker, did you read [this doc](https://github.com/horovod/horovod/blob/master/docs/docker.md)?
yes

**Your question:**
Please ask your question here.

I run horovod with pytorch  and  got this error
```
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient 
```
I have meet this when run with pytorch and notice that the docker default value of shm-size is 64M. 
so I change the shm-size of pod like this
```
apiVersion: v1
kind: Pod
metadata:
  name: shm
  containers:
  - args:
    - mpirun -np 4 -H localhost:4 -x python train.py  
    command:
    - /bin/bash
    - -c
    image: uber/horovod:0.15.2-tf1.12.0-torch1.0.0-py3.5
    imagePullPolicy: Always
    name: shm
    resources:
      limits:
        cpu: "32"
        memory: 128Gi
        nvidia.com/gpu: "4"
      requests:
        cpu: "32"
        memory: 128Gi
        nvidia.com/gpu: "4"
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
        - SYS_RESOURCE
        - SYS_PTRACE
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
  restartPolicy: Never
  volumes:
  - emptyDir:
      medium: Memory
      sizeLimit: "81920"
    name: dshm

```

and no matter how big the shm size is set. the pod Failed by the reason 
```
Usage of EmptyDir volume "dshm" exceeds the limit "102400"
```

 when run this in pytorch with 1GPU, set the shm-size=10G, solved `insufficient shared memory`.

so there is any different betwwen primary  pytorch and pytorch with horovod?
