### ISSUE TITLE
Trying to install Horovod from a fresh conda environment (with tensorflow) and nothing seems to work

### ISSUE THREAD

**Issue by illumidas-agn** [horovod/horovod#2138]
**Environment:**
1. Framework: (TensorFlow)
2. Framework version:
3. Horovod version: 0.19.5
4. MPI version: -
5. CUDA version: -
6. NCCL version: -
7. Python version: 3.6
8. OS and version: Ubuntu
9. GCC version: -

**Your question:**
Please ask your question here.

Looked through all the available open questions. Currently trying to run go-explore (https://github.com/uber-research/go-explore/tree/master/policy_based) and I have only managed to make horovod work once for whatever reason. 

I need it built with tensorflow (aka horovod.tensorflow) and when I try to force the tensorflow flag during installation I get a 10 page log dump which is hard to discern what it actually needs. 

How do I get horovod running?

Im not sure what im doing wrong, I've tried everything else

**Comment by tgaddair** [comment]
Hey @illumidas-agn, have you taken a look at the Conda install guide [here](https://github.com/horovod/horovod/blob/master/docs/conda.rst)?

If you're still having issues after going through that, feel free to provide log output showing where things are breaking.

**Comment by illumidas-agn** [comment]
Hi @tgaddair, Im gonna go through that and let you know how it goes

**Comment by illumidas-agn** [comment]
Im trying to run this from a server where I am not the sudo user, is there any alternatives using pip or conda install?

**Comment by tgaddair** [comment]
Where are you running into permissions issues?  @davidrpugh, do you have some thoughts on this?

If you don't need to use conda, you can also opt to install everything through pip in a virtual environment.  But the important thing is you'll need to make sure the CUDA devtools are available when building in NCCL support.  If this is an issue, you may want to see if you can run in a containerized environment.

**Comment by illumidas-agn** [comment]
I need to be able to run the CUDA Toolkit as sudo and sadly im not an admin, therefore I cant install it the conventional way. I was able to make it run on my local virtual environment and then when I transfered it into the server that's when I ran into issues. Tried the entire day to get horovod and cuda to run.

I can ask the admin of the server to install it if theres no quick fix for this

**Comment by tgaddair** [comment]
Either that or setting up Docker/Singularity would probably be the easiest way, yes.  It's certainly possible to install locally (see: https://stackoverflow.com/questions/39379792/install-cuda-without-root), but managing the correct environment variables will likely be a challenge.

**Comment by illumidas-agn** [comment]
I see, in that case ill contact the server admin and ill get back to you if everything works. Thank you for your help

**Comment by davidrpugh** [comment]
@illumidas-agn you should be able to install Horovod using Conda without root privileges. You will need to use the `cudatoolkit-dev=10.1` package from Conda Forge channel. The environment file below should work (you will still need to other files referenced in the Conda install guide).

```yaml
name: null

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - cmake=3.16
  - cudatoolkit-dev=10.1
  - cudnn=7.6
  - cupti=10.1
  - cxx-compiler=1.1
  - jupyterlab=2.1
  - matplotlib=3.2
  - mpi4py=3.0 # installs cuda-aware openmpi
  - nccl=2.5
  - nodejs=13
  - pip=20.1
  - pip:
    - mxnet-cu101mkl==1.6.* # makes sure installed prior to horovod
    - -r file:requirements.txt
  - python=3.7
  - pytorch=1.5
  - tensorboard=2.1
  - tensorflow-gpu=2.1
  - torchvision=0.6 
```

Note that I have bumped a lot of version numbers from what is in the current guide. @tgaddair I will test this and then update the install guide accordingly. Perhaps an explicit indication that you will need to use the `cudatoolkit-dev` approach if you don't have permissions to install CUDA toolkit as root.

**Comment by illumidas-agn** [comment]
The project im trying to run requires python 3.6, but I will see whether 3.7 works, will keep you updated

**Comment by davidrpugh** [comment]
@illumidas-agn Then just change the Python version to 3.6. Shouldn't impact the build.

**Comment by illumidas-agn** [comment]
I see, I just see it listed in the requirements that you have posted above

**Comment by davidrpugh** [comment]
@illumidas-agn I pin the version numbers in my environment file to the most recent versions of the various dependencies for which I am able to get a successful build. Other combinations of version numbers may also work just fine. Also note that if you only need TensorFlow then you can probably get by with the following environment file which should build more quickly.

```yaml
name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - cudatoolkit-dev=10.1
  - cudnn=7.6
  - cupti=10.1
  - cxx-compiler=1.1
  - jupyterlab=2.1
  - matplotlib=3.2
  - mpi4py=3.0 # installs cuda-aware openmpi
  - nccl=2.5
  - nodejs=13
  - pip=20.1
  - pip:
    - -r file:requirements.txt
  - python=3.7 # python=3.6 should also work!
  - tensorboard=2.1
  - tensorflow-gpu=2.1
```

In the above environment file I have dropped the PyTorch and MXnet dependencies.
