### ISSUE TITLE
Very Slow running with ResNet50 using real dataset 

### ISSUE THREAD

**Issue by Jeffwan** [horovod/horovod#779]
I am testing ResNet50 using synthetic data and real dataset. Now I experience two issues. 

1. For synthetic data, scaling efficiency can not hit 90% if I use > 4 nodes. Anything I can optimize? 
2. For real data, performance is really bad, just ~200-300 images/second, I use EFS and I don't think that's the problem of storage, I tried host storage and it's same result.  I am trying to understand why there's a big difference. I download timeline.json and looks like there's lots of time wasting on shuffle and negotiation_all_reduce.. Can someone help take a look? 

synthetic - 1 worker 8 gpus
![image](https://user-images.githubusercontent.com/4739316/51719270-a829a800-1ffd-11e9-96af-a6eccf86b0a2.png)
logs: https://gist.github.com/Jeffwan/012cf867a0e0c3757980123a94e085e8

real - 1 worker 8 gpus
![image](https://user-images.githubusercontent.com/4739316/51719296-c099c280-1ffd-11e9-9d4b-9f93da1ed4e8.png)
Looks like preprocessing takes long time and more NEGOTIATE_ALLREDUCE there.
logs: https://gist.github.com/Jeffwan/5e286b291ab6c0f333153d290a6d1368

Synthetic metrics
GPU | ResNet50  | Scaling Efficiency
-- | -- | --
1 | 872 | 1
8 | 6679 | 95.70%
16 | 12828 | 91.90%
32 | 23870 | 85.50%
64 | 47195 | 84.50%
128 | 89783 | 80.40%

Cluster Spec
*Instance Type:* 2 x p3.16xlarge  (25Gbps)
*GPU:* 8 x Tesla V100-SXM2-16GB/ 8 x Tesla V100-SXM2-32GB
*CNI*: amazon-k8s-cni:v1.3.0-22-g5cce382c
*CUDA/cuDNN*: 7.4.1.5-1+cuda9.0
*NCCL*: 2.3.5-2+cuda9.0
*NVIDIA Accelerated Graphics Driver*: Linux-x86_64 (396.26)
*Tensorflow Version*: v1.12.0
*Container Image*: uber/horovod:0.15.2-tf1.12.0-torch1.0.0-py2.7

Configuraiton

```
        command:
          - mpirun
          - "-mca"
          - "btl_tcp_if_exclude"
          - "lo,docker0"
          - "-mca"
          - "pml"
          - "ob1"
          - "-mca"
          - "btl"
          - "^openib"
          - "--bind-to"
          - "none"
          - "-map-by"
          - "slot"
          - "-x"
          - "LD_LIBRARY_PATH"
          - "-x"
          - "PATH"
          - "-x"
          - "NCCL_DEBUG=INFO"
          - "-x"
          - "NCCL_MIN_NRINGS=8"
          # - "-x"
          # - "NCCL_CHECKS_DISABLE=1"
          - "-x"
          - "HOROVOD_TIMELINE=/data/timeline.json"
          #- "-x"
          #- "HOROVOD_HIERARCHICAL_ALLREDUCE=1"
          - "-x"
          - "HOROVOD_FUSION_THRESHOLD=16777216"
          - python
          - scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py
          - --data_format=NCHW
          - --batch_size=256
          - --model=resnet50
          - --num_batches=100
          - --optimizer=sgd
          - --variable_update=horovod
          - --horovod_device=gpu
          - --data_name=imagenet
          - --data_dir=/data/imagenet
          - --use_fp16=True
          #- --datasets_num_private_threads=8
        resources:
          limits:
            nvidia.com/gpu: 8
        volumeMounts:
          - name: persistent-storage
            mountPath: /data
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: efs-claim
```
